name: currency_swap
channels:
  - pytask
  - conda-forge

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - matplotlib
  - pandas
  - pip
  - pytask>=0.0.11
  - pytask-latex>=0.0.10


  - pytest
  - pytest-cov
  - python=3.8
  - python-graphviz

  - pandas-datareader

  - virtualenv=20.0.33

  - seaborn
  
  - web3

  - pip:

    - pre-commit

    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex



    